baseurl = "https://example.com/"                                                              # Include trailing slash
title = "Hugo Themes"
theme = "hugo-swift-theme"
author = "Steve Francia"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = true
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13

[pagination]
disableAliases = false
pagerSize = 6
path = 'page'
